### ISSUE TITLE
[OT] Import and extend libraries

### ISSUE THREAD

**Issue by pablorsk** [FountainJS/generator-fountain-webapp#101]
I'm using a fresh [fountain-webapp (angular1 + webpack + typescript)](https://gist.github.com/pablorsk/cc43629c53a6500aea9342491652218d)

Why can I do this?

```
import * as angular from 'angular';
import 'ts-angular-jsonapi';
```

But when I do this

```
import * as angular from 'angular';
import * as jsonapi from 'ts-angular-jsonapi';
```

I get this error?

```
ERROR in ./src/index.ts
(22,23): error TS2307: Cannot find module 'ts-angular-jsonapi'.
```

What I need change on `ts-angular-jsonapi` for a correct import?

More info: I need import ts-angular-jsonapi and extend the classes.

**Comment by micaelmbagira** [comment]
You just need to `npm install ts-angular-jsonapi`

**Comment by micaelmbagira** [comment]
Hi @pablorsk  the reason is that they export 'ts-angular-jsonapi' (`module.exports = 'ts-angular-jsonapi';`) but the name of the module is `rsJsonapiConfig`. 
So you need to use `angular.module('app', ['rsJsonapiConfig'])` and in order to import this module you can do `import 'ts-angular-jsonapi';` (you also can do `import * as jsonapi from 'ts-angular-jsonapi';` but it will be useless because you won't use `jsonapi`).

I think you should open an issue on their project because this is definitely a bad behaviour.

**Comment by pablorsk** [comment]
Thanks @micaelmbagira!

I'm working on `ts-angular-jsonapi`, and the comunity is just me for now :P. I trying to learn the correct way for build a library imported by npm and it work with fountain-web-app.

Inject angular dependecies work fine, no problem with that. The problem is I can't extend classes with typescript, like

```
class myClass extends Jsonapi.Resource {

}
```

And get a error like this:

```
Uncaught ReferenceError: Jsonapi is not defined
```

I know is not a problem with fountain, but really I need help for migrate my libraries and work fine with `generator-fountain-webapp`. With `generator-gulp-angular` works fine.

**Comment by micaelmbagira** [comment]
What is `Jsonapi` ?

**Comment by zckrs** [comment]
@micaelmbagira  IMO 

http://jsonapi.org/

**Comment by pablorsk** [comment]
Thanks for your help, again. :)

[Jsonapi is a module of `ts-angular-jsonapi`, and is defined](https://github.com/reyesoft/ts-angular-jsonapi/blob/master/src/library/resource.ts) like this:

```
module Jsonapi {
    export class Resource implements IResource {
        public schema: ISchema;
    }
}
```

On `generator-gulp-angular` work fine inserted with `<script />` tag via bower. I'm migrating to fountain, but I like use `npm` and `import`, like you suggest on examples.

We are very grateful for your help.

Yes @zckrs, `ts-angular-jsonapi` is a library for [jsonapi.org](http://jsonapi.org/) :)

**Comment by micaelmbagira** [comment]
What you can do is `export module Jsonapi` and then `class myClass extends Jsonapi.Resource`

**Comment by pablorsk** [comment]
WOOOOOOOOOW I ask (bad formulation :P), search and work a lot with this, and the answer was very simple: **Is not possible use import on .TS file when you try import a .JS file**. I need use require()

Also, node module need a specific lines. I make a simple example if somebody need [make Typescript Node Modules](https://github.com/pablorsk/typescript-node-module-example).

Thanks a lot @micaelmbagira!

**Comment by pablorsk** [comment]
Just a tip for people with a same problem.

Another (and better) solution is add this to tsconfig.json

``` json
    "compilerOptions": {
        "allowJs": true
    }
```
