### ISSUE TITLE
npm run build won't work

### ISSUE THREAD

**Issue by kdsingharneja** [FountainJS/generator-fountain-webapp#104]
I am sorry but I just do not have time to give you all the details you asked for. Very sorry.

I had issues with angular and its dependencies. Updated those and npm install worked fine. But now `npm run build` gives me error.  [npm-debug-log.txt](https://github.com/FountainJS/generator-fountain-webapp/files/410162/npm-debug-log.txt)

Now take a step back for a second. Do you think this helps folks who are trying to adopt your generator when the basic install and basic steps don't even work? I could not even get to writing my app code. I can investigate further and will resolve the issues, but I won't. Rather pick up a starter repo at this time. Adding this issue for benefit of others.

**Comment by clabnet** [comment]
Me too. I agree.

**Comment by zckrs** [comment]
> I am sorry but I just do not have time to give you all the details you asked for. Very sorry.

Me too @kdsingharneja.  We can't help you if you don't want take time to clearly explain what you don't have understood. 😔

**Comment by kdsingharneja** [comment]
I was't expecting a different response. :+1:
