### ISSUE TITLE
update angular2 to rc5

### ISSUE THREAD

**Issue by axe-me** [FountainJS/generator-fountain-webapp#108]
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc5-2016-08-09

**Comment by micaelmbagira** [comment]
Hi, @ShaneXie It's in the pipe, but currently there is a big issue https://www.github.com/angular/angular/issues/10618, so we might probably wait until RC6 because it's a blocking bug...

**Comment by axe-me** [comment]
@micaelmbagira cool. thx for quick response.

**Comment by thegrid22593** [comment]
@micaelmbagira First off love the generator! Keep it up! Any update on RC5? The thread you posted seems to have found a solid solution.

**Comment by micaelmbagira** [comment]
Yes there is a workaround for rc5. But the problem has been fixed and this will be shipped with rc6, so we are waiting for rc6.

**Comment by axe-me** [comment]
@micaelmbagira rc6 is [here](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-rc6-2016-08-31)

**Comment by Swiip** [comment]
Yep, it takes a lot of modifications to our templates to use new NgModules and TestBed. Work is in progress...

**Comment by chendachao** [comment]
Could please inform me once upgrade to rc 6 has been done. I struggled weeks at rc 6.  😕

**Comment by Swiip** [comment]
You can follow our work on `rc6` branches. Most of the changes are in https://github.com/FountainJS/generator-fountain-angular2/tree/rc6

**Comment by chendachao** [comment]
I'm more interesting in UT part with rc 6 + karma + jspm, but I didn't see it in the branch https://github.com/FountainJS/generator-fountain-angular2/tree/rc6, do you have a plan or simple demo?

Thanks in advance.

**Comment by Swiip** [comment]
Sorry, I started with Webpack, the SystemJS adjustements are not done yet.

**Comment by tlenex** [comment]
angular 2.0 final is ready out there

**Comment by Swiip** [comment]
Yep, initial rc5 branch renamed rc6 will be the 2.0 finally :)

But it doesn't change much, most of the work is about using NgModules...

**Comment by zckrs** [comment]
We have release a new version https://github.com/FountainJS/generator-fountain-webapp/releases/tag/v1.0.0-rc1 who contains Angular2 final stable version.
