### ISSUE TITLE
Angular 1 webapp "index.html not found" on angular:factory creation

### ISSUE THREAD

**Issue by rowild** [FountainJS/generator-fountain-webapp#110]
Hi,

I follow this tutorial:
https://devdactic.com/wordpress-rest-angularjs/

In my case, I create the project via fountainjs, using "Angular 1", "SASS", and "no scripts with bower" as options.

At some point in the tutorial, a factory should be created like so:

```
yo angular:factory wpFactory 
```

But I get this error:

```
me: /Volumes/_II_/SITES/_ZZZ_Wordpress_453/wp-content/themes/project
↣ yo angular:factory wpFactory 
   Unable to find app/index.html. Reference to services/wpFactory.js not added.

   create app/scripts/services/wpfactory.js
   create test/spec/services/wpfactory.js
```

Indeed, the index is one level higher in the folder hierarchy, which seems perfectly normal.

I wonder, if this is a fountainjs problem or whether there is a place, where I can tell fountainjs to change the location where to look for an index.html.

Thanks!

**Comment by micaelmbagira** [comment]
Calling `yo angular` will call **this generator https://github.com/yeoman/generator-angular !**
If you want to use our subgenerator to create a service, not a factory (we don't provide subgenerator for factory), you can find doc here https://github.com/FountainJS/generator-fountain-angular1#sub-generators
