### ISSUE TITLE
Karma fails with imported scss files

### ISSUE THREAD

**Issue by ufoscout** [FountainJS/generator-fountain-webapp#113]
Hi all,

we are using the fountain-generator 0.6.0 with typescript, sass and webpack.
In our ts files we import scss resources like:
`import './sideMenu.component.scss';`

This works fine when serving the application (npm run serve) but it causes a failure in Karma:

```
$ npm run test
...
ERROR in ./src/app/main/menu/sideMenu.component.scss
Module parse failed: .../src/app/main/menu/sideMenu.component.scss Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
| .sticky {
|     position: sticky;
|     top: 10px;
 @ ./src/app/main/menu/sideMenu.component.ts 2:0-36
...
```

**Comment by micaelmbagira** [comment]
Hi @ufoscout 
If in your test, you import  a file which contains a scss import, you need to add the appropriate loader in `conf/webpack-test.conf.js`. You can copy the `(css|scss)` loader that is in `conf/webpack.conf.js`.

**Comment by ufoscout** [comment]
@micaelmbagira Thanks, it solved the issue. 

Shouldn't it be set by default?

**Comment by micaelmbagira** [comment]
It depends, we decided to import scss only in index.js and then to use scss '@import'. Then, as we don't test index.js we don't add scss-loader in webpack test conf...
