### ISSUE TITLE
Angular 1 + Webpack: WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by danpoland** [FountainJS/generator-fountain-webapp#118]
## Description

`WARNING: Tried to load angular more than once.` is displayed in browser consoles when running `gulp serve:dist` for angular 1 + webpack apps.

The warning is not displayed when running `gulp serve`.

The warning points to the complied vendor js file.
### Error Message & Stack Trace

`WARNING: Tried to load angular more than once.`
### Config

Copy the content from `.yo-rc.json`:

``` json
{
  "generator-fountain-angular1": {
    "version": "0.7.0",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "babel",
      "ci": [],
      "css": "scss",
      "resolved": "C:\\Users\\testuser\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "hello",
      "router": "uirouter"
    }
  }
}
```
## Relevant Links

This issue can be recreatred by simiply running the generator for the selections below, then running `gulp serve:dist`.

```

? Which JavaScript framework do you want? Angular 1
? Which module management do you want? Webpack with NPM
? Which JS preprocessor do you want? Pure old JavaScript
? Which CSS preprocessor do you want? CSS
? Which Continuous Integration platform do you want? (Press <space> to select)
? Do you want a sample app? Just a Hello World
? Would you like a router? None
```
## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and yo. Run the following to get it quickly:

```
Node.js v6.3.0
win32 10.0.14393

yo --version
1.8.4

npm --version
3.10.3
```

**Comment by vedmaque** [comment]
Actually, same problem with any setup with webpack. Vendor scripts are duplicating.
