### ISSUE TITLE
How can I start using node_modules instead of bower for front-end dependencies?

### ISSUE THREAD

**Issue by TheOpti** [FountainJS/generator-fountain-webapp#119]
I would like to start a new project using Angular 1.x and Gulp, but it uses wiredep by default, which loads front-end dependencies. I would like to stop using bower, and keep all my front-end libraries as well as dev dependencies (tests, gulp, etc.) in node_modules. What is the easiest way to remove bower?

**Comment by micaelmbagira** [comment]
When generating a project with FountainJS generator, you can select Webpack instead of Bower

**Comment by TheOpti** [comment]
I know, but I don't want to use Webpack.

**Comment by micaelmbagira** [comment]
Mmh you want to use wiredep and node_modules ?

**Comment by TheOpti** [comment]
I want to stop using wiredep and start loading all my dependencies from node_modules.

**Comment by micaelmbagira** [comment]
Well if you want to use npm modules you need a module loader. So either Webpack or SystemJS (or browserify but we don't provide this option yet).
