### ISSUE TITLE
[Angular2 Webpack]How to load a script in node_modules?

### ISSUE THREAD

**Issue by dereklin** [FountainJS/generator-fountain-webapp#121]
I need to load this in index.html:

```
<script src="node_modules/zone.js/dist/zone.js"></script>
```

But it says it's not found.  What is the right way to load it?

**Comment by Swiip** [comment]
You can't just use `import 'zone.js/dist/zone';` in your `index.html`?

If you really want this, you have to map the `node_modules` dir in your browsersync. The conf looks like: `server.routes = {'/node_modules': 'node_modules'};`.

**Comment by dereklin** [comment]
I got it working importing 'zone.js/dist/zone' in index.ts
