### ISSUE TITLE
Upgrade to Newer Router

### ISSUE THREAD

**Issue by HomeboxJim** [FountainJS/generator-fountain-webapp#127]
The current router version of @angular/router is not working. It is the deprecated "RouterConfig" one. It would be nice if these scaffolded projects were updated to use the newer "@Routes" version of the @angular/router.

**Comment by Swiip** [comment]
New API will be used in the next release, the PR (with angular 2 final) is almost complete.

**Comment by zckrs** [comment]
We have release a new version https://github.com/FountainJS/generator-fountain-webapp/releases/tag/v1.0.0-rc1 who contains Angular2 final stable version.

**Comment by HomeboxJim** [comment]
Nice!

Thanks for the awesome generator. :)
