### ISSUE TITLE
Error with angular2@2.0.0-beta.7

### ISSUE THREAD

**Issue by guillaumeleone** [FountainJS/generator-fountain-webapp#13]
Hello, 

```
? Which JavaScript framework do you want? Angular 2
? Which module management do you want? Webpack with NPM
? Which CSS preprocessor do you want? SASS
? Which JS preprocessor do you want? TypeScript
```

IMO there is a pb with the last angular version (currently 2.0.0-beta.7). It was downloaded when we have generated the template

```
── angular2@2.0.0-beta.7 
```

There was many errors at the execution:

```
ERROR in /workspace/node_modules/angular2/src/core/linker/compiler.d.ts
(12,50): error TS2304: Cannot find name 'Promise'.
...
```

I think it would be safer to use "angular2": "2.0.0-beta.0" without ^ in the dependencies.
Also, your generator doesn't seem to work.

My workaround, when I've finished to generate my template :

```
$ npm install angular2@2.0.0-beta.0 rxjs@5.0.0-beta.0
```

Thanks

**Comment by Swiip** [comment]
Yep, allowing to auto update ng2 could not be the best option right now. Still, I think it's possible to find a way to make it works with the last beta version.

The whole thing is not really stable yet sorry, you still have to make some adjustment after the generation. It should be better in later release.

**Comment by Swiip** [comment]
Try with the new 0.5 release which ship a lot newer rc1 version.
