### ISSUE TITLE
Update Angular 2 to the official 2.0.0 release

### ISSUE THREAD

**Issue by oferze** [FountainJS/generator-fountain-webapp#131]
https://github.com/angular/angular/blob/master/CHANGELOG.md#200-2016-09-14

**Comment by eduardoborges** [comment]
Please :)

**Comment by vaske** [comment]
When I pick up option "Angular 2" I'm not able to download anything seems like it's broken.

**Comment by Swiip** [comment]
It's nearly finished https://github.com/FountainJS/fountain/pull/52. Please wait a bit more for us to be able to stabilize this.

Also, linked to #108

**Comment by oferze** [comment]
@Swiip once it's done, I'll emphasize it much more in http://fullstack.info/angular-2-quickstarter-bootstrap-boilerplate-projects/ because I really love this project.

**Comment by vaske** [comment]
awesome, we are waiting for it :)

**Comment by zckrs** [comment]
We have release a new version https://github.com/FountainJS/generator-fountain-webapp/releases/tag/v1.0.0-rc1 who contains Angular2 final stable version.

**Comment by oferze** [comment]
@Swiip @zckrs Awesome! I've updated my blog post accordingly.
