### ISSUE TITLE
Download page broken

### ISSUE THREAD

**Issue by chadfurman** [FountainJS/generator-fountain-webapp#133]
Steps: 
1. http://fountainjs.io/download
2. "React"
3. "Webpack"
4. "Babel"
5. "Sass"
6. "Hello World"
7. click "Download"

-- nothing happens.

Using the "npm install" method for now.

**Comment by Swiip** [comment]
Tested for the same options and it works for me. What browser did you use?

There is a bit of JS involved, have you opened a console to check if there is any errors?

**Comment by chadfurman** [comment]
1) It's working now.  _shrug_
2) There were no JavaScript errors
3) Google Chrome for Linux: Version 53.0.2785.116 (64-bit)
