### ISSUE TITLE
how styling react-redux todomvc works ?

### ISSUE THREAD

**Issue by orkideh** [FountainJS/generator-fountain-webapp#135]
Hello,
I created project with config bellow: 

? Which JavaScript framework do you want? React
? Which module management do you want? Webpack with NPM
? Which JS preprocessor do you want? TypeScript
? Which CSS preprocessor do you want? SASS
? Which Continuous Integration platform do you want? CircleCi
? Do you want a sample app? Redux TodoMVC
? Would you like a router? React router

I added my own component with new `.scss` file but nothing from this components will affect my application and event after running application with `gulp serve` after editing any `.scss` files even index.scsss  application will not be refreshed or changes will not be applied.

Is Any one could help me please to solve it and make style works ?
thank you

**Comment by micaelmbagira** [comment]
You have to add `import 'myfile.scss'` in your `index.ts`. So far, the app only uses styles from a library, so that's why you have to add this line yourself.
