### ISSUE TITLE
livereload breaks after build

### ISSUE THREAD

**Issue by spaceghostu** [FountainJS/generator-fountain-webapp#139]
Generate a project

```
yo fountain-webapp
```

Use following settings

Which JavaScript framework do you want? Angular 1

Which module management do you want? None with Bower and script injection

Which JS preprocessor do you want? Pure old JavaScript

Which CSS preprocessor do you want? CSS

Which Continuous Integration platform do you want? (none)

Do you want a sample app? A working landing page

Would you like a router? Angular UI Router

Edit a file and save, liveReload should work and your change should show up in browser.

Now build the app

```
gulp build
```

Now edit a file and save, liveReload works, but change does not show up in browser untill you build again.

**Comment by Swiip** [comment]
Livereload only works in the dev workflow with `npm run serve`.

With `build` or `serve:dist` you launch the optimization process which is slow and doesn't rebuild automatically.

**Comment by spaceghostu** [comment]
Using `npm run serve` doesn't make a difference.

After some testing, I realise that it's only when you edit HTML files the changes don't show up, I think this is because .tmp/templateCacheHtml.js doesn't update on LiveReload. If i delete .tmp/templateCacheHtml.js the LiveReload starts working properly again
