### ISSUE TITLE
JavaScript Source Maps don't work?

### ISSUE THREAD

**Issue by pablorsk** [FountainJS/generator-fountain-webapp#140]
Hi! I'm trying to get a better messages on browser debug console, but the erros allways refer to index.ts file.

![](http://s9.postimg.org/4hvx364cf/screenshot194.png)
### Config

Copy the content from `.yo-rc.json`:

``` json
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "techs",
      "router": "uirouter"
    }
  }
}
```

```
Node.js v6.7.0
linux 4.4.0-38-generic
$ yo --version
1.8.4
$ npm --version
3.10.3
```

Any ideas how can I config correctly sourcemap for a better experience?

**Comment by zckrs** [comment]
Hi,

You used a very old version of generator-fountain-angular1 (0.6.0)

Our last version is:

```
❯ npm info generator-fountain-angular1 version
1.0.0-rc1

```

**Comment by pablorsk** [comment]
I do the same command

``` bash
npm info generator-fountain-angular1 version
1.0.0-rc1
```

Like you see, I have the last version of `generator-fountain-angular1`. But, when I run again  `yo  generator-fountain-webapp` no get any update on configuration file or files.

Also, I try generate a clean project  but generate again a same file

```$cat .yo-rc.json 
{
  "generator-fountain-angular1": {
    "version": "0.6.0",
    "props": {
....

```

Any ideas?
```

**Comment by pablorsk** [comment]
solved!

Sorry, I need run `sudo yo` and update....

**Comment by destegabry** [comment]
## Description

I also having source maps problem and can't figure out what's happening here!

Seems css and js maps are not included well, so Chrome fails parsing them.

Everything works after removing any sourcemaps references from `gulp_tasks/build.js`.

This is my `index.html` source after build:

``` html

<!doctype html>
<html>
  <head>
    <base href="/">
    <meta charset="utf-8">
    <title>Consulenza Evoluta</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="maps/styles/app-9d8e8afbe5.css.map">

  </head>
  <body ng-app="isp.consevo.mobiliare"><script id="__bs_script__">//<![CDATA[
    document.write("<script async src='/browser-sync/browser-sync-client.js?v=2.17.5'><\/script>".replace("HOST", location.hostname));
//]]></script>

    <div class="outer-wrapper ng-cloak" ui-view></div>
  </body>

  <script src="maps/scripts/vendor-4f783951f0.js.map"></script>

  <script src="maps/scripts/app-3d21e51fc6.js.map"></script>
</html>
```

### Error Message & Stack Trace

```
Resource interpreted as Stylesheet but transferred with MIME type application/json: "http://localhost:3000/maps/styles/app-9d8e8afbe5.css.map".
vendor-4f783951f0.js.map:1 Uncaught SyntaxError: Unexpected token :
app-3d21e51fc6.js.map:1 Uncaught SyntaxError: Unexpected token :
```

### Config

``` json
{
  "generator-fountain-angular1": {
    "version": "1.0.0-rc1",
    "props": {
      "framework": "angular1",
      "modules": "inject",
      "js": "js",
      "ci": [],
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "techs",
      "router": "uirouter"
    }
  }
}
```

## Environment

```
Node.js v5.3.0
darwin 15.6.0
$ yo --version
1.8.5
$ npm --version
4.0.0
```

**Comment by chakgou** [comment]
Desactivate sourcemap in task build.  All js and css files are minified when you start gulp serve:dist.
All js and css files aren't minified when you start gulp serve

`function build() {
  const partialsInjectFile = gulp.src(conf.path.tmp('templateCacheHtml.js'), {read: false});
  const partialsInjectOptions = {
    starttag: '',
    ignorePath: conf.paths.tmp,
    addRootSlash: false
  };

  const htmlFilter = filter(conf.path.tmp('_.html'), {restore: true});
  const jsFilter = filter(conf.path.tmp('__/_.js'), {restore: true});
  const cssFilter = filter(conf.path.tmp('*_/_.css'), {restore: true});

  return gulp.src(conf.path.tmp('/index.html'))
    .pipe(inject(partialsInjectFile, partialsInjectOptions))
    .pipe(useref())
    .pipe(jsFilter)
   // .pipe(sourcemaps.init())
    .pipe(ngAnnotate())
    .pipe(uglify({preserveComments: uglifySaveLicense})).on('error', conf.errorHandler('Uglify'))
    .pipe(rev())
   // .pipe(sourcemaps.write('maps'))
    .pipe(jsFilter.restore)
    .pipe(cssFilter)
    .pipe(sourcemaps.init())
    .pipe(cssnano())
    .pipe(rev())
   // .pipe(sourcemaps.write('maps'))
    .pipe(cssFilter.restore)
    .pipe(revReplace())
    .pipe(htmlFilter)
    .pipe(htmlmin())
    .pipe(htmlFilter.restore)
    .pipe(gulp.dest(conf.path.dist()));
}
`

**Comment by A-Allam** [comment]
I have the same problem, any help?

**Comment by pablorsk** [comment]
sorry, I update generator and it fix on some PCs, but on my PC don't. I can't detect the specific problem.

**Comment by pablorsk** [comment]
@A-Allam intenta actualizar tus herramientas globales con npm. En linux deberías ir a `/usr/lib/node_modules/` and run `sudo npm update`

**Comment by destegabry** [comment]
I have the same problem, fixed commenting all `.pipe(source maps...` lines, but I would like to have the source maps enabled to better debug production code.
