### ISSUE TITLE
Problem with webpack watch on Vagrant

### ISSUE THREAD

**Issue by lciolecki** [FountainJS/generator-fountain-webapp#146]
Hello everybody!

I have created an angular1 + webpack + babel + ui router + todoMVC application using yo fountainjs-webapp. Everething works fine on local enviroment (my PC).  But when I run gulp serve on Vagrant and do some changes in my app source code then gulp / webpack watch doesn't see changes and doesn't regenerate app. 

I have fixed this case on gulp.watch by add `{ usePolling: true }` in gulpfile.js. But I can't fix this problem in webpack.watch. I have found information about polling webpack there: http://webpack.github.io/docs/configuration.html#watchoptions-poll but when I add 

```
watchOptions: {
poll: true
}
```

in conf/webpack.conf.js then nothing happens... Also I have created issue on webpack repository: https://github.com/webpack/webpack/issues/3099 but none can help me.. Maybe someone with you had the same problem and have resolved allready that?

I tested that on nodejs 4.6 and 6.7, npm: 3.10.

**Comment by lciolecki** [comment]
There https://github.com/lciolecki/fountainjs-example I have put example fountainjs webapp with Vagrant. 
1. Run local enviroment:
   Go to project path run `npm install` and next `gulp serve`. When You do some changes in app/**.js then application will reload all.
2. Run Vagrant enviroment:
   Do all installation from project (virtualbox, vagrant, ansible, ansible-galaxy) and go to project and run:
   - `vagrant ssh`
   - go to catalog /vagrant
   - run `gulp serve`

And now when You do some changes in app/**.js then application will not reload..

**Comment by lciolecki** [comment]
Problem was solved in https://github.com/webpack/webpack/issues/3099#issuecomment-253307056. By adding {poll: true} in  in gulp_tasks/weback.js:

if (watch) {
webpackBundler.watch({ poll: true }, webpackChangeHandler);
} else {
webpackBundler.run(webpackChangeHandler);
}

And adding `{ usePolling: true }` in gulp.js:

`gulp.watch(conf.path.tmp('index.html'), { usePolling: true }, reloadBrowserSync);`

**Comment by zckrs** [comment]
Nice. Thank you for your reporting and solution.  I will mark this issue as future recipe
