### ISSUE TITLE
Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by 0101adm** [FountainJS/generator-fountain-webapp#149]
## Description

Throwing an error when running 'gulp serve'.
### Error Message & Stack Trace

/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:19
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
### Config

{
  "generator-fountain-angular1": {
    "version": "1.0.0-rc1",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "typescript",
      "ci": [
        "travis"
      ],
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular1/generators/app/index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "todoMVC",
      "router": "uirouter"
    }
  }
}
## Environment

OSX 10.11.6
Node.js v6.8.0
darwin 15.6.0
yo 1.8.5
npm 3.10.8

**Comment by zckrs** [comment]
Duplicate https://github.com/FountainJS/generator-fountain-webapp/issues/53#issuecomment-225375085
