### ISSUE TITLE
Twitter Bootstrap not working with bower and Angular 1.5.8

### ISSUE THREAD

**Issue by sickpalmex** [FountainJS/generator-fountain-webapp#156]
Hi, what is the correct way to install ui.bootstrap with bower? I installed with `bower install -S angular-bootstrap` and added `ui.bootstrap` dependence on `index.js` but does not work.

My `index.js`:

`angular
  .module('app', ['ui.router', 'ui.grid', 'ui.bootstrap']);`

My `bower.json`

 `{
  "name": "fountain-inject",
  "version": "0.0.1",
  "dependencies": {
    "angular": "^1.5.8",
    "angular-ui-router": "1.0.0-beta.1",
    "angular-ui-grid": "3.2.1",
    "bootstrap": "^3.3.7",
    "angular-bootstrap": "^2.2.0",
    "jquery": "^3.1.1"
  },
  "devDependencies": {
    "angular-mocks": "^1.5.0"
  }
}`

Thanks!!

**Comment by ripper2hl** [comment]
why not publish your project  ?

**Comment by micaelmbagira** [comment]
@sickpalmex Please provide the details of the errors you have.
