### ISSUE TITLE
Cannot select sample app type

### ISSUE THREAD

**Issue by DaAwesomeP** [FountainJS/generator-fountain-webapp#16]
When I get to the part in the prompt when it asks "Do you want a sample app?" I cannot select the hello world option. The arrow keys down work on that prompt. I used Angular 2, Webpack with NPM, SASS, and Typescript.

**Comment by micaelmbagira** [comment]
Which version are you using ? Is it the `v0.3.0`, the one you can find on NPM ?

**Comment by zckrs** [comment]
@DaAwesomeP We just release `v0.4.0` and I try with your option. (NPM3, Node4)

It works.

![screenshot](https://cloud.githubusercontent.com/assets/3020368/14499631/63306470-019f-11e6-9517-f1fc5096902a.png)
