### ISSUE TITLE
Seed app with angular 2 framework is not getting downloaded .

### ISSUE THREAD

**Issue by rajathms** [FountainJS/generator-fountain-webapp#162]
I'm trying to download a seed app, with angular  2 framework but it's not working .

angular2-inject-js-css-router-todoMVC.zip is not getting downloaded  

It's  working with other Frameworks but not with Angular 2 .

**Comment by rajathms** [comment]
Sorry, 
I tried with bower modules ,that's my bad.

**Comment by Swiip** [comment]
Angular 2 is not published on Bower and so we're not providing this combination.

I know the download page should prevent to select this combination but that's not the case at the moment.

**Comment by rajathms** [comment]
@Swiip  yea UI should not allow the user to choose those options
