### ISSUE TITLE
Adding fonts support to build task (Angular1 + Bower)

### ISSUE THREAD

**Issue by eonardol** [FountainJS/generator-fountain-webapp#166]
Hi all,
is it possible to add a "fonts task" to build process? Basic example:

    gulp.task('fonts', fonts);
    function fonts(){
        return gulp.src([
            'bower_components/font-awesome/fonts/*',
            'bower_components/bootstrap/fonts/*'
        ])
        .pipe(gulp.dest(path.join(conf.path.dist(), '/fonts/')));
    }

**Comment by micaelmbagira** [comment]
Hi @eonardol 
So far, Fountain is quite minimalist and doesn't provide a configuration for every case. But you can configure your own gulp tasks.

**Comment by SpencerKaiser** [comment]
@eonardol I've also been struggling with including font awesome so I would love to see this added! Definitely going to use your code snippet, thanks for posting!

**Comment by Swiip** [comment]
Fonts have been the most problematic feature of gulp-angular so I don't want it to be included in Fountain. We stay out of this.

Anyway, any recipe in a PR will be considered

**Comment by pixelbacon** [comment]
@Swiip I realize the reasoning... But by supporting bower as part of the generator, 3rd party font management is indeed an inherited responsibility. Two additional gulp tasks would be able to take care of this, both local and bower being supported.

Please consider reopening this ticket, as it comes as a waterfall effect of supporting bower, and then I can create a PR.

Bootstrap <v3, Font-Awesome... To name a few industry standards that as of right now, are widely used that have to be put in each and every time... Defeating the point of using a generator and bower in it's simplest nature.
