### ISSUE TITLE
npm install packages UNMET PEER DEPENDENCY 

### ISSUE THREAD

**Issue by jinnabaalu** [FountainJS/generator-fountain-webapp#186]
issue in installing packages 

UNMET PEER DEPENDENCY babel-core@^6.0.0

 UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

UNMET PEER DEPENDENCY webpack@2.1.0-beta.27

UNMET PEER DEPENDENCY zone.js@0.6.26

npm WARN @angular/router@3.4.9 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/http@2.4.9 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.9 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.9 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN extract-text-webpack-plugin@2.1.0 requires a peer of webpack@^2.2.0 but none was installed.
npm WARN webpack-fail-plugin@1.0.6 requires a peer of webpack@^1.9.11 but none was installed.
npm WARN babel-loader@6.4.0 requires a peer of babel-core@^6.0.0 but none was installed.

here is my .yo-rc.json file 

{
  "generator-fountain-angular2": {
    "version": "1.0.0-rc2",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "ci": [
        "jenkins"
      ],
      "css": "css",
      "resolved": "/usr/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "sample": "techs",
      "router": "router"
    }
  }
}

**Comment by Swiip** [comment]
Please update to generator 1.0.0 final and it should work.

**Comment by jinnabaalu** [comment]
My bad, Worked, we can close this issue
