### ISSUE TITLE
Routing.

### ISSUE THREAD

**Issue by elimence** [FountainJS/generator-fountain-webapp#45]
I'm not familiar with the structure and design of this generator as it's very different from regular Angular 1 projects. I'm wondering how routing is handled here. I haven't found any documentation for that around and the Angular 2 styleguide wasn't much help.

**Comment by micaelmbagira** [comment]
As we use the component concepts, you should use Angular 1 component router which is based on Angular 2 router. Here is the documentation https://docs.angularjs.org/guide/component-router

**Comment by micaelmbagira** [comment]
You can also use angular UI router with the following syntax: 

```
.state('state.component', {
  url: "/route",
  template: '<mycomponent></mycomponent>'
})
```

**Comment by elimence** [comment]
thanks 👍
