### ISSUE TITLE
unable to debug.

### ISSUE THREAD

**Issue by denlabs** [FountainJS/generator-fountain-webapp#49]
Trying to set breakpoints on the app in Intellij, but breakpoints being totally ignore (not even active when starting a debugger).  I've setup a debug configuration as documented here https://blog.jetbrains.com/webstorm/2015/09/debugging-webpack-applications-in-webstorm/ however not having any success.  I've left the devtool as is in the webpack.conf ('cheap-module-eval-source-map')

the debugger seems to start fine, but no breakpoints are recognized.  Also, I should point out that the webpack:///. src directory only has *scss files and no js files.  Not sure if that matters or not? 

Any ideas?

**Comment by micaelmbagira** [comment]
Can it be because you are running our dev server (browsersync) and not the WebStorm built-in web server ?

**Comment by zckrs** [comment]
Sadly we don't use Webstorm and there are no responses since 24 days.
