### ISSUE TITLE
Testing generator with angular1: problem with 

### ISSUE THREAD

**Issue by pablorsk** [FountainJS/generator-fountain-webapp#5]
```
$ node --version
v4.2.6

$ npm install -g yo gulp-cli
$ npm install -g generator-fountain-webapp
$ yo fountain-webapp
❯ Angular 1 
❯ Webpack with NPM 
❯ SASS 
❯ TypeScript 

$ gulp serve

[12:41:17] Loading /home/rsk/desarrollo/fountain/gulp_tasks/partials.js
module.js:328
    throw err;
    ^
Error: Cannot find module 'gulp-minify-html'
```

Then, I try with

```
npm install -d gulp-minify-html
```

But now, when run "gulp serve", I get this:

```
[12:44:17] Using gulpfile ~/desarrollo/fountain/gulpfile.js
/usr/local/lib/node_modules/gulp/bin/gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^
TypeError: Cannot read property 'apply' of undefined
```

Bug or I'm doing something wrong? (thanks :P)

(I try with ES2015 too, but I obtain the same error).

**Comment by zckrs** [comment]
- 1) Yeah `gulp-minify-html` missed
- 2) You should have TSD installed in global `npm install -g tsd`
- 3) Use `npm run serve` who use local gulp installed instead of `gulp serve`

EDIT: run `tsd install` too 
EDIT2: **Project under heavy development**

**Comment by pablorsk** [comment]
wow, your work is very advanced. We will wait for the generator to bring examples of components, filters, etc.

Your solution work fine :)

**Comment by jessepinuelas** [comment]
@pablorsk I if you `npm install -g gulp-cli` it should fix the cannot read property error 'apply' of undefined. Then you can continue to use gulp serve.

**Comment by AnalyzePlatypus** [comment]
@jessepinuelas's suggestion fixed this issue by me
