### ISSUE TITLE
HTML watcher only works once

### ISSUE THREAD

**Issue by karin-n** [FountainJS/generator-fountain-webapp#50]
First off - great work on the generator! 

I have been running into an issue where the html change watcher only works once. E.g. I run 'gulp serve', make a change to an html file and the first time the browser refreshes successfully, but when I change the same html file again, the change is not detected. I can change a different html file which also triggers a browser refresh once. If I change a .ts file, the change is always detected. I have run the generator a few times and the issue is always reproducible.

Following is my setup and the configuration options I have used: 

OS: OSX 10.11.5
Node version: 4.2.4
NPM version: 3.9.5

Framework: Angular 1
Modules manager: Webpack with NPM
CSS preprocessor: SASS
JS preprocessor: TypeScript
Sample app: Techs

Any help would be much appreciated!

**Comment by zckrs** [comment]
Hi,

Can you replace "watch" function in gulpfile.js to

```
function watch(done) {
  gulp.watch(conf.path.src('app/**/*.html'), cb => {
    browserSync.reload();
    cb();
  });
  done();
}
```

**Comment by karin-n** [comment]
Perfect! Thanks so much for the quick response :)

**Comment by zckrs** [comment]
Should be fixed in the next release
