### ISSUE TITLE
Throws "this.env.adapter.promt(...).then is not a function" Error When Run

### ISSUE THREAD

**Issue by JimLynchCodes** [FountainJS/generator-fountain-webapp#56]
I install the generator with `_npm install -g fountain_` and then run `_yo fountain-webapp_`

But this error appears:

`TypeError: this.env.adapter.prompt(...).then is not a function
    at Base.prompt (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/base.js:232:45)
    at fountainPrompting (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/fountain-generator/lib/Base.js:77:17)
    at prompting (/usr/local/lib/node_modules/generator-fountain-webapp/generators/app/index.js:15:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/base.js:431:23)
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/run-async/index.js:26:25
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/run-async/index.js:25:19
    at /usr/local/lib/node_modules/generator-fountain-webapp/node_modules/yeoman-generator/lib/base.js:432:9
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immedi`

**Comment by zckrs** [comment]
Can you complete issue template? 

https://github.com/FountainJS/generator-fountain-webapp/blob/master/.github/issue_template.md#environment

**Comment by zckrs** [comment]
IMO you have old version of `yo`

**Comment by JimLynchCodes** [comment]
Sorry, I meant to check this when I got home yesterday but I forgot. I'll try to update yo and then close the issue if it works.

**Comment by JimLynchCodes** [comment]
yo --version:
1.7.0

npm --version:
3.8.6

Then I do `sudo npm install yo -g` and then yo --version gives me this:
1.8.4

Then the fountain generator itself said it had a new update, so I updated that too. Is there a shell command yo check the version of a generator? If I do `fountain-webapp --version` it doesn't work, and `yo fountain-webapp --version` just returns 1.8.4.

Anyway, it worked!
Coming from the regular Gulp-Angular generator, these are some weird questions you ask. :)

Still awesome though! 👍

**Comment by zckrs** [comment]
Thank you @JimTheMan.  If you have support question you can use our Slack
https://fountain-slack.herokuapp.com

And I see you use `sudo` to install npm package.  IMO you should read this guide. 
https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md

**Comment by zubair-khanzada** [comment]
upgrade yo version. its work for me

**Comment by aheinhoang** [comment]
not work for me

**Comment by GantMan** [comment]
I'm having this problem and it's only when my generator, runs a generator.  Works fine when I prompt in a subgenerator that I run from the CLI.  I've tried to find and destroy all old versions of `yo`as described but this really has me scratching my head.

### Update:  Got it working

Had to remove all node modules of my generator, then remove all from my project.  Then install generator node modules, then link, then install generator in project.   Quite a dance.
