### ISSUE TITLE
Question - Remove maps on build

### ISSUE THREAD

**Issue by Martin-Andersen** [FountainJS/generator-fountain-webapp#59]
Hi,  How can I remove the source maps on build to production? and is there a way to color the menu bar to reflect if the app are running against a test or production database?

I would also like to remove the angular html cache and just minify the HTML

**Comment by JPFeli** [comment]
Are you using webpack?  
If so, for HTML I would use [raw-loader](https://github.com/webpack/raw-loader) for Webpack and then import HTML normally.

Thanks.

**Comment by zckrs** [comment]
Hi @Martin-Andersen 

To help you we need more informations on your app.

Can you follow https://github.com/FountainJS/generator-fountain-webapp/blob/master/.github/issue_template.md
