### ISSUE TITLE
Feature request: Keep tsconfig.json in the project root folder.

### ISSUE THREAD

**Issue by fdcastel** [FountainJS/generator-fountain-webapp#61]
## Description

Keep `tsconfig.json` in the project root folder. Do not move it to `/conf/ts.conf.json`.
## Rationale
- Every editor out there which supports TypeScript looks for `./tsconfig.json` in root project folder. Moving this file to `/conf/ts.conf.json` breaks this convention and disables the most advanced features of editors (e.g. code insight).
- The **[TypeScript Handbook](http://www.typescriptlang.org/docs/handbook/tsconfig-json.html)** is very clear about this subject:

> The presence of a tsconfig.json file in a directory indicates that the directory is the root of a TypeScript project. 
- An experienced TypeScript user coming to a new project generated by FountainJS would find awkward to not find the `tsconfig.json` file in the root folder.
- Lastly, the current non-standard location of this file requires the following section to be added in `/conf/webpack*.conf.js` files

```
  ts: {
    configFileName: 'conf/ts.conf.json'
  },
```

Moving the file back to the root folder allow us to remove this section entirely from these three files (`webpack.conf.js`, `webpack-dist.conf.js` and `webpack-test.conf.js`).
## Relevant Links

List of editors supporting TypeScript:

https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support

**Comment by micaelmbagira** [comment]
Fixed in 0.7.0 (just released) 😉
