### ISSUE TITLE
Site web: Dead links

### ISSUE THREAD

**Issue by tienslebienz** [FountainJS/generator-fountain-webapp#63]
Hi,
there's some dead link on your website especially on http://fountainjs.io/doc

**Comment by zckrs** [comment]
Hi @tienslebienz,

Can you give me the differents links ?

**Comment by tienslebienz** [comment]
http://fountainjs.io/doc/DESIGN.md

**Comment by vazh** [comment]
this one,

[DESIGN.md#L19](https://github.com/FountainJS/fountainjs.github.io/blame/d516f43ab6156f4d916b5db47919fc549d508cb9/src/data/docs/getting-started.md#L19)
