### ISSUE TITLE
Proper Method to inject module into Angular 1 project using NPM

### ISSUE THREAD

**Issue by getglad** [FountainJS/generator-fountain-webapp#64]
## Description

This is more a 'help' question than anything, but should probably get documented once answered.

In `gulp-angular`, to add a module I would install it through bower, and add it to the module line, and `ngInject` would take it from there.

`angular.module('ng1m', [ 'ui.router', 'ngMaterial',...`

It looks like in the new `fountain-webapp`, I need to:
1. Run `npm install angular-material --save`
2. Add an import statement to `index.module.js` - `import 'angular-material';`
3. Add it to my `.module` - `angular.module('app', ['ui.router', 'ngMaterial',...`
4. And maybe something else...?

Using this process I can find my JavaScript files under sources in Chrome Dev Tools - `webpack://./~/angular-material/angular-material.js?ec27`

The CSS appears to be injected at the top of the DOM, right after `head`

My HTML template: `<md-button> Flat Button </md-button>`
Renders into: `<button class="md-button md-ink-ripple" type="button" ng-transclude="" aria-label="Flat Button"><span class="ng-scope"> Flat Button </span></button>`

But `.md-button` and `.md-ink-ripple` have no classes applied.

Happy to provide more detail, but didn't know if I was missing something obvious here.
### Error Message & Stack Trace

No errors.
### Config

```
{
  "generator-fountain-angular1": {
    "version": "0.5.4",
    "props": {
      "framework": "angular1",
      "modules": "webpack",
      "js": "babel",
      "css": "scss",
      "resolved": "C:\\Users\\...\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular1\\generators\\app\\index.js",
      "namespace": "fountain-angular1",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "todoMVC",
      "router": "uirouter"
    }
  }
}
```
## Environment

```
node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v4.4.6
win32 6.1.7601

yo --version
1.8.4

npm --version
3.10.2
```

**Comment by JPFeli** [comment]
This is a nice addition.
I don't know if this method will work for every npm package (looking at you Ionic). But in general it's a good way to do it.
Webpack has many other options, you can even separate those vendors in a different js file.

Thanks!

**Comment by JPFeli** [comment]
Sorry, I just figured out, you need the css files missing. You'll need to
import those too.

**Comment by micaelmbagira** [comment]
With Webpack, the only difference is that you need to run `npm install` instead of `bower install`. Then `angular.module('app', ['ui.router', 'ngMaterial']` is enough, you shouldn't need to `import` it

**Comment by kuhnroyal** [comment]
I had to import it as well otherwise it wouldn't work.

**Comment by micaelmbagira** [comment]
So you need to fo the following:
- `npm install angular-material angular-animate angular-aria --save`
- Add the following lines on top of `index.js`:

```
import ngMaterial from 'angular-material';
import 'angular-material/angular-material.css';
angular
  .module('app', [ngMaterial])
```

Then, it works.

**Comment by heshamelmasry77** [comment]
okay but some but some other we can't use npm for example
 https://github.com/devmark/angular-slick-carouse
what we do now 🍶
