### ISSUE TITLE
Contributing to Docs?

### ISSUE THREAD

**Issue by JimLynchCodes** [FountainJS/generator-fountain-webapp#66]
Hi. I Ike the fountains.io docs a lot, but I've found a bug (it says "wepack", and I'm 99% sure it should be "webpack". I could just change this myself and submit a pull request, but are is the documentation an open source project as well?

**Comment by micaelmbagira** [comment]
Hi @JimTheMan, sure you can submit a PR on this repo

**Comment by zckrs** [comment]
@JimTheMan you can create PR on https://github.com/FountainJS/fountainjs.github.io/tree/dev/src/data

Documentation are written in MD.

**Comment by zckrs** [comment]
Can we close this issue and see your contributions into https://github.com/FountainJS/fountainjs.github.io?

**Comment by JimLynchCodes** [comment]
Ok, thanks! 👍
