### ISSUE TITLE
Error On Freshly Scaffolded Angular 2 Todo-MVC

### ISSUE THREAD

**Issue by JimLynchCodes** [FountainJS/generator-fountain-webapp#67]
## Description

Errors on `npm run serve` after fresh install of angular 2 ToDo-MVC.
### Error Message & Stack Trace

![redux-fountain-library-scaffold_ _gulp_ _npm_term_program_apple_terminal_term_xterm-256color_shell__bin_bash_ _134x33_and_new_issue_ _fountainjs_generator-fountain-webapp_](https://cloud.githubusercontent.com/assets/5354163/16530884/1c306ab6-3f98-11e6-87ef-4887766abd44.png)

This error shows in my command shell, but it seems to finish as if it's ok. Then I go to localhost:3000 in the browser, and it's just a white screen with empty console.

```
COPY THE ERROR MESSAGE, INCLUDING STACK TRACE HERE
```

ERROR in ./src/routes.ts
(14,42): error TS2345: Argument of type '() => TransitionPromise' is not assignable to parameter of type 'string | (($injector: any, $location: any) => string)'.
  Type '() => TransitionPromise' is not assignable to type '($injector: any, $location: any) => string'.
    Type 'TransitionPromise' is not assignable to type 'string'.

ERROR in ./src/index.ts
(14,45): error TS2305: Module '"/Users/jim/git2/Redux-Fountain-Library-Scaffold/node_modules/ui-router-ng2/ng2"' has no exported member 'UiView'.
Child 
### Config

Copy the content from `.yo-rc.json`:
{
  "generator-fountain-angular2": {
    "version": "0.5.4",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "todoMVC",
      "router": "uirouter"
    }
  }
}
## Relevant Links

https://github.com/JimTheMan/Redux-Fountain-Library-Scaffold
## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and yo. Run the following to get it quickly:

```
npm: 3.8.6
node: v6.0.0
yo: 1.8.4
```

**Comment by DFGU** [comment]
I have also encountered this error with angular 2 + typescript. I do not recieve the error with angular 2 + ES2016 or pure javascript, but in all cases the ui-view never loads for any of the example applications.

I am currently new to angular 2, but after I gain some understanding I will attempt to troubleshoot the issue and report my findings. 

It might be worth noting I have no issues running the angular 1, or react examples.

**Comment by micaelmbagira** [comment]
Hi, the error is cause by last version of `ui-router`, the upgrade should be part of the next release.
Meanwhile, you need to replace `UiView` with `UIView`, it will fix the first issue.

**Comment by DFGU** [comment]
Thanks @micaelmbagira
