### ISSUE TITLE
Handle project updates

### ISSUE THREAD

**Issue by jmls** [FountainJS/generator-fountain-webapp#68]
## Description

How do you handle fountain project updates ? For example, let's say I've created 20 projects using fountain. Then, a bug is fixed in a gulpfile or build file, template etc - how do I roll that bugfix out to all 20 projects ?

Do I have to manually upgrade each one ?

**Comment by zckrs** [comment]
Hi,

There is no upgrade provide by Yeoman.
You should update the generator by `npm -g install generator-fountain-webapp` and rerun `yo fountain-webapp` in your current project.

But be careful. Before upgrade I suggest you to create a branch in your project.

This post should help you http://stackoverflow.com/a/18500003
