### ISSUE TITLE
Requirements mem-fs

### ISSUE THREAD

**Issue by ggaulard** [FountainJS/generator-fountain-webapp#7]
I need to install mem-fs and mem-fs-editor to be able to launch a yo fountain-webapp.

**Comment by Swiip** [comment]
Strange, I just checked the sources, it's in transitive deps of yeoman. We only use it directly in fountain-generator tests and the deps is present in dev dep of fountain-generator.

Your npm install didn't failed? I don't see how this package could have not been installed with a standard npm install.

**Comment by ggaulard** [comment]
I've updated my node version after installing yeoman and the generator.
It may come from this.
