### ISSUE TITLE
Webpack to use `html-loader`

### ISSUE THREAD

**Issue by JPFeli** [FountainJS/generator-fountain-webapp#71]
Webpack could use `html-loader` (from webpack) instead of `gulp-angular-templatecache`.
Benefits: relative paths in component's templates.

Let me add a use-case.
- Create a component
- Provide a templateURL (`'app/somecomponent/template.html`)
- Decide to move the component folder
- Component needs review to work

Provide a `template` and you can move the component folder since path is relative. (`import template from './template.html'`)

Does it make sense? I'm missing any benefit from not using templatecache?
I don't know, maybe is too specific.

**Comment by Swiip** [comment]
We already use this for Angular 2, it could be interesting to use it also for Angular 1 indeed. It would simplifies build process.

**Comment by micaelmbagira** [comment]
Fixed in 0.7.0 😉
