### ISSUE TITLE
eslint-plugin-babel-3.3.0.tgz - 502 Bad Gateway

### ISSUE THREAD

**Issue by mradzinski** [FountainJS/generator-fountain-webapp#72]
502 Bad Gateway while trying to generate an Angular 2 Project with TypeScript.

npm ERR! fetch failed https://registry.npmjs.org/eslint-plugin-babel/-/eslint-plugin-babel-3.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/eslint-plugin-babel/-/eslint-plugin-babel-3.3.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 502
npm ERR! fetch failed https://registry.npmjs.org/eslint-plugin-babel/-/eslint-plugin-babel-3.3.0.tgz
npm ERR! Linux 4.6.3-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.2.2
npm ERR! npm  v3.10.3

npm ERR! fetch failed with status code 502

**Comment by micaelmbagira** [comment]
Did you try running `npm install` again ?

**Comment by mradzinski** [comment]
Yes, and although it seems to install all dependencies the project fails to run when invoking _gulp_

**Comment by zckrs** [comment]
Can you provide your .yo-rc.json ?

**Comment by mradzinski** [comment]
My .yo-rc.json looks like:

```
{
  "generator-fountain-angular2": {
    "version": "0.6.0",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "hello",
      "router": "none"
    }
  }
}
```

**Comment by micaelmbagira** [comment]
What is the exact error you are having with gulp ?

**Comment by mradzinski** [comment]
It's working fine now, but it seems _eslint-plugin-babel-3.3.0.tgz_ file availability is a bit unstable. I tried generating another project today and got the same 502 error for about an hour or so and then the file became available again and everything worked fine. It might be some npmjs.org issue...

**Comment by micaelmbagira** [comment]
Not from our side: https://github.com/npm/npm/issues/13284
