### ISSUE TITLE
using bootstrap

### ISSUE THREAD

**Issue by meddahmane** [FountainJS/generator-fountain-webapp#75]
Dear All,

I am trying to use bootstrap with fountain generator throw bower install --save angular-bootstrap , it's installed but when I use  any component or css class from bootstrap showing a basic  html element.

Any help or suggestion

**Comment by Naeoth** [comment]
Same problem with **npm** modules... I tried to install the module 'angular-material' and 'material-design-icons', the JS files are added but not the CSS. The only way I found to add the stylesheet is to input '@import 'pathToCssFile.css' in the index.scss file (the CSS files are in bower_components or in node_modules directory...) But I think it is not a good practice to do it that way.

**Comment by micaelmbagira** [comment]
@meddahmane  `angular.module('myModule', ['ui.bootstrap']);`
But this is not related to FountainJS: https://angular-ui.github.io/bootstrap/

@Naeoth https://github.com/FountainJS/generator-fountain-webapp/issues/64#issuecomment-230701663

**Comment by SeLoRBIS** [comment]
@meddahmane You can see this response at this topic : [https://github.com/twbs/bootstrap/issues/16663#issuecomment-112881352](https://github.com/twbs/bootstrap/issues/16663#issuecomment-112881352)
Actually the solution is to add this in the bower.json file : 

```
"overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.css"
      ]
    }
  }
```
