### ISSUE TITLE
TypeScript Errors with Angular 2

### ISSUE THREAD

**Issue by thegrid22593** [FountainJS/generator-fountain-webapp#77]
Hello, generator works fine when choosing Angular 2 and TypeScript, however I am getting the following errors right off the bat with the TypeScript compiler. This all happens on a fresh install of fountain generator hello world.
### Error Message & Stack Trace

```
TS2304: Cannot find name 'Promise'.
TS2304: Cannot find name 'Map'.
TS2304: Cannot find name 'SetConstructor'.
etc.
```

```
TS1219: Experimental support for decorators is a feature that is subject to change in a future release. Set the 'experimentalDecorators' option to remove this warning.

```

^ the ts.config.json has experiementalDecorators = true but it still shows this error yet the app still renders to the page.
### Config

``` json
{
  "generator-fountain-angular2": {
    "version": "0.6.0",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/usr/local/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "hello",
      "router": "uirouter"
    }
  }
}
```
## Environment

npm -v 3.9.3
yo -v 1.8.4
node -v 6.2.1
Mac OS 10.11.5
JetBrains PHP Storm 2016.1 Fully up to date

**Comment by micaelmbagira** [comment]
Can you check if you have `es6-shim` in `typings/globals` ?

**Comment by thegrid22593** [comment]
Yes I do. Here is the structure.

```

-typings
   -globals
       - es6-shim
       - jasmine
       - node
       - require

```

**Comment by micaelmbagira** [comment]
I cannot reproduce it, could you try to regenerate the project and if it still occurs, send a github repo ?

**Comment by thegrid22593** [comment]
Hi, so I reorganized everything into component organization. Now everything is compiling just fine.
I will try to see if I can recreate the problem again to see if there is a serious issue.

**Comment by thegrid22593** [comment]
Here is a repo with this issue. https://github.com/thegrid22593/angular2-router

**Comment by micaelmbagira** [comment]
I tried your repo, I didn't have any error in the terminal but I had few in the browser console. The reason is that `.js` and `.js.map` files are generated at compilation. 
You should create a `tsconfig.json` file at the root of your project with the content of `conf/ts.conf.json` and add `compileOnSave: false` (and also remove the generated `.js` and `.js.map` files) it should work then. Actually, I just made you a pull request https://github.com/thegrid22593/angular2-router/pull/1

**Comment by thegrid22593** [comment]
Thank you!
