### ISSUE TITLE
importing extrnal libraries to components

### ISSUE THREAD

**Issue by EdenEdk** [FountainJS/generator-fountain-webapp#78]
## Description

Hey guys! i really need you help, i'm using the seed and it is great.
**Before ill start explaining the problem, just wanted to note that although my project is not fully updated with the latest updates, I just made today a new 'HelloWorld' project with the latest updates and the problem still accur**
but i came across a problem i couldn't solve no matter where i searched or that i've tried.. :disappointed:
i cant import external libraries to my components.
For example, when i try to import socket.io-client 
my import line is: 
`import * as io from 'socket.io-client'`
and it won't find the module..
iv'e tried with other libraries too.
Again and again iv'e tried every combination, using even '../../../node_modules' and etc.. before the node_modules and still, not working..
my selected project contains the follow:
-Angular2
-webpack
-typescript
-less
-hello world example

I searched the internet for a solution and tried various things but nothing worked..
please help me solve this, and if you can **please specify a guide of doin so, with the steps for the solution..**
Thanks!!
### Error Message & Stack Trace

```
error TS2307: Cannot find module 'socket.io-client'.
```
### Config

``` json
{
  "generator-fountain-angular2": {
    "version": "0.5.4",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "css": "less",
      "resolved": "C:\\Users\\Eden\\AppData\\Roaming\\npm\\node_modules\\generator-fountain-webapp\\node_modules\\generator-fountain-angular2\\generators\\app\\index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "hello",
      "router": "uirouter"
    }
  }
}
```
## Environment

```
Node.js v6.2.2
win32 6.1.7601

yo version: 1.8.4

npm version: 3.10.2
```

**Comment by Swiip** [comment]
I reproduced with TS. Retry with Babel and no error. There is something wrong with socket-io and TS.

Before concluding "it's not our fault" I want to digg if we can configure Webpack to make it work.

**Comment by micaelmbagira** [comment]
I managed to make it work by running `typings install dt~socket.io-client —global —save`
and then `import * as io from 'socket.io-client';`
And at last, if it's not already there, you need to add `/// <reference path="../typings/index.d.ts" />` on top of the code.

**Comment by EdenEdk** [comment]
@micaelmbagira thanks!!! it worked! finally!
