### ISSUE TITLE
WebStorm resolve issue

### ISSUE THREAD

**Issue by ceelian** [FountainJS/generator-fountain-webapp#8]
Webstorm cannot resolve angular2/core in the hello.ts file with typescript and systemjs.

<img width="405" alt="screen shot 2016-02-11 at 14 36 17" src="https://cloud.githubusercontent.com/assets/116299/12977781/3451de3e-d0cd-11e5-915d-e19c5ec7cfda.png">

**Comment by Swiip** [comment]
I don't use Webstorm, how works it with systemjs? In some way it has to look in the config.js to understand JSPM deps... The JSPM configuration is quite standard I dont see what we can do.

**Comment by wojciechpolak** [comment]
I had this same problem with IntelliJ IDEA (Ultimate) just yesterday. They support Bower, but currently no JSPM. As a temporary solution you have to install the JSPM dependencies (from package.json) with `npm install`. Then add this extra flags to the TypeScript compiler (tsc) in your IDE's settings: `--moduleResolution node --experimentalDecorators --target ES6`
