### ISSUE TITLE
Cannot read property 'apply' of undefined - Gulp Serve

### ISSUE THREAD

**Issue by gabrieldevelops** [FountainJS/generator-fountain-webapp#85]
I'm getting this error when running gulp serve:

C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js:129
    gulpInst.start.apply(gulpInst, toRun);
                  ^

TypeError: Cannot read property 'apply' of undefined
    at C:\Program Files\nodejs\node_modules\gulp\bin\gulp.js:129:19
    at _combinedTickCallback (node.js:370:9)
    at process._tickCallback (node.js:401:11)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:141:18)
    at node.js:933:3

Yo version: 1.8.4
NodeJS version: v5.7.0
NPM version: 3.10.5
Bower version: 1.6.8

TodoMVC template project.

Any idea???

**Comment by micaelmbagira** [comment]
Probably because you don't have gulp 4 installed in global.
You can either run `./node_modules/.bin/gulp serve` or `npm run serve`. Both commands will use the local gulp which is gulp 4.

**Comment by zckrs** [comment]
Install `gulp-cli` in global

**Comment by gabrieldevelops** [comment]
I solved this problem as follows:
- Updated the NodeJS
- Updated the NPM (npm install -g npm)
- Installed global gulp -cli (npm install --global gulp-cli)

Thanks #micaelmbagira and #zckrs
