### ISSUE TITLE
Absolute dist css file path should be relative

### ISSUE THREAD

**Issue by ufoscout** [FountainJS/generator-fountain-webapp#88]
## Description

The path to the final css in the dist/index.html file is an absolute one, e.g.:

```
<link href="/index-d74e4f4ab3bcfbb06d0bbc88c1ad2bda.css" rel="stylesheet"></head>
```

this is caused by this configuration entry in the webpack-dist.conf.js file:

```
new ExtractTextPlugin('/index-[contenthash].css')
```

This is an issue because it does not permit to deploy the webapp in a different context (e.g. www.mysite.com/something/index.htm does not work) than the root one.
So the path should be relative by default; this can easily be achieved removing the "/" from the ExtractTextPlugin configuration:

```
new ExtractTextPlugin('index-[contenthash].css')
```

In addition, the paths to JS files are instead all relatives:

```
<script type="text/javascript" src="vendor-1ba394c679ccc175943c.js"></script>
<script type="text/javascript" src="app-1ba394c679ccc175943c.js"></script>
```
### Config

``` json
{
  "generator-fountain-angular2": {
    "version": "0.6.0",
    "props": {
      "framework": "angular2",
      "modules": "webpack",
      "js": "typescript",
      "css": "scss",
      "resolved": "/home/ufo/Programs/node-v6/lib/node_modules/generator-fountain-webapp/node_modules/generator-fountain-angular2/generators/app/index.js",
      "namespace": "fountain-angular2",
      "argv": {
        "remain": [],
        "cooked": [],
        "original": []
      },
      "skip-cache": false,
      "skip-install": false,
      "sample": "techs",
      "router": "router"
    }
  }
}
```
## Environment

```
Node.js v6.2.2
linux 4.4.0-24-generic
yo 1.8.4
npm 3.9.5
```

**Comment by micaelmbagira** [comment]
Hi @ufoscout thanks for the report and for following the template issue, it should be fixed in the next release 😉
