### ISSUE TITLE
Generate project in parent directory caused by .yo-rc

### ISSUE THREAD

**Issue by Slashgear** [FountainJS/generator-fountain-webapp#89]
# Generate project in parent directory caused by .yo-rc

If there is a **.yo-rc** file in the parent directory of the project directory in which you want to use fountainjs, the project is generated in the parent not in the child.

```
.
└── test
    ├── .yo-rc
    └── projectdir
```

This may be a problem with yeoman.

```
yo 1.84
node 6.2.2
npm 3.9.5
```

**Comment by micaelmbagira** [comment]
https://github.com/yeoman/yo/issues/327
