### ISSUE TITLE
Watcher for typescript not working

### ISSUE THREAD

**Issue by ceelian** [FountainJS/generator-fountain-webapp#9]
With `npm run serve` changing the "Hello World" string in the hello.ts doesn't reload the webapp with browsersync. systemjs, typescript, angular2

**Comment by Swiip** [comment]
The watch / livereload / hmr is not ready yet. There is a lots of situation where the reloading is not what we expect, we have to work on that.

**Comment by zckrs** [comment]
That should be fixed in v0.4.0 release

**Comment by zckrs** [comment]
Yep fixed I just try.
