### ISSUE TITLE
Build for specifics environments

### ISSUE THREAD

**Issue by pablorsk** [FountainJS/generator-fountain-webapp#96]
Hi!

Any recipe for building for differents environments?

On `generator-gulp-angular` we have this: https://github.com/Swiip/generator-gulp-angular/blob/master/docs/recipes/environment-specific-build.md. Any recommendation with this new generator?

Thanks!

**Comment by micaelmbagira** [comment]
When you have run `gulp serve`, you use the dev configuration, when you run `gulp build` or `gulp serve:dist` you use the "production" configuration. But they all depend on the toolset you are using.

**Comment by benjamincharity** [comment]
@pablorsk We also needed the ability to use different environment configs so we needed a better solution than just webpack configs. (eg need to build locally against staging environment etc)

Might not be the most elegant solution, but it was quick:

---

#### Create a top level directory to hold your config files:

```
./config/
  local.json
  staging.json
  production.json
```

These files look something like this:

```
{
    "CONFIG": {  // this is the name of the constant that will be exposed
        "name": "local",
        "api": {
            "endpoint": "http://localhost:8080/api"
        },
        ...
}
```

#### Add a new file under `gulp_tasks/` called `config.js`:

``` javascript
const gulp = require('gulp');
const conf = require('../conf/gulp.conf');
const rename = require('gulp-rename');
const argv = require('yargs').argv;
const ngConstant = require('gulp-ng-constant');

// Get the environment from the command line
// Default to dev if nothing is passed
var environment = argv.env || 'local';

gulp.task('config', config);

function config(done) {
    gulp.src('./config/' + environment + '.json')
        .pipe(ngConstant({
            name: 'my.config', // this is the name of the generated module
            wrap: 'es6',
        }))
        .pipe(rename('index.js'))
        .pipe(gulp.dest(conf.path.src('app/components/config')))
    ;

    done();
}
```

#### Then add this new task to the primary `gulpfile.js` before the normal build tasks run:

``` javascript
const gulp = require('gulp');
const HubRegistry = require('gulp-hub');
const browserSync = require('browser-sync');
const conf = require('./conf/gulp.conf');

// Load some files into the registry
const hub = new HubRegistry([conf.path.tasks('*.js')]);

// Tell gulp to use the tasks just loaded
gulp.registry(hub);

gulp.task('build', gulp.series(gulp.parallel('config', 'other', 'webpack:dist')));
gulp.task('test', gulp.series('config', 'karma:single-run'));
gulp.task('test:auto', gulp.series('config', 'karma:auto-run'));
gulp.task('serve', gulp.series('webpack:watch', 'watch', 'browsersync'));
gulp.task('serve:dist', gulp.series('default', 'browsersync:dist'));
gulp.task('default', gulp.series('clean', 'build'));
gulp.task('watch', gulp.series('config', watch));

function reloadBrowserSync(cb) {
    browserSync.reload();
    cb();
}

function watch(done) {
    gulp.watch(conf.path.src('app/**/*.html'), reloadBrowserSync);
    done();
}
```

#### Now you can include your config:

``` javascript
import '../components/config';

angular.module('myModule', [
    'my.config',
    'toastr',
    ...
]);

// Then simply inject CONFIG into a controller and access properties:
// {{ CONFIG.api.endpoint }}
```

This allows us to run `gulp --env staging` or `gulp serve --env production` etc.

**Comment by pablorsk** [comment]
thanks a lot @benjamincharity!! 

I did not know how to create parameters as "--env" :+1:

**Comment by elliottregan** [comment]
I didn't think it was a good idea to use BrowserSync in production. Is that the intention, or are we expected to build and serve the files with a separate server?
