### ISSUE TITLE
generate webapp landingpage, when removing component 'main' creates build issue

### ISSUE THREAD

**Issue by mattiLeBlanc** [FountainJS/generator-fountain-webapp#97]
Hi,

I started with the webapp generator and created an Angular1, TS, Stylus, Webpack project with a landingpage.

When I started to replace parts and removed elements from the landingpage I noticed that I couldn't build anymore.

```
ERROR in multi app
Module not found: Error: Can't resolve './.tmp/templateCacheHtml.ts' in '/Users/User/www/webApp'
 @ multi app
```

I tracked the issue down to the line `.component('app', main)` in the index.ts.
When I remove the main component (which I don't need) the build process breaks.
When I put it back (with it's TS and HTML template) the build is fine.

I then tried the generator with the HelloWorld option, and with that one I am allowed to remove the 
`.component('app', hello)` and it won't break.

I am not sure what is going on, but at first I thought it was something I did while developing my angular app. During `serve` I did not get any errors, just the error on build.

Hope you guys can reproduce this and hopefully fix it because it gave me a bit of a headache.

EDIT: I didn't believe it has anything to do with the existence of a main component. That wouldn't make sense. 
The error message `multi app` is not ringing a bell with me right now, but I assume it has to do with the name `app` being used multiple times??

**Comment by micaelmbagira** [comment]
@mattiLeBlanc Can you send a github ? I think it would be easier for me 😉

**Comment by mattiLeBlanc** [comment]
Hi @micaelmbagira 

https://github.com/mattiLeBlanc/fountaintest

After clone, do a npm install and then npm run build
Of course, the issue is not presenting itself right now.
Both version I had locally stopped displaying the issue and build correctly.
Very strange, can't it be a gulp or npm related thing?

Maybe you see something wrong the the setup. 
Peter Leibiger suggested to remove all templatecache references, but not sure how to do that. Just remove tasks from gulp?

**Comment by kuhnroyal** [comment]
Made you a PR with changes that I use: https://github.com/mattiLeBlanc/fountaintest/pull/1

**Comment by micaelmbagira** [comment]
Nice @kuhnroyal, should we close the issue ?

**Comment by mattiLeBlanc** [comment]
@kuhnroyal Thanks mate.
So you think that weird templatecache error could have something to do with the mix of HTML and pug?

**Comment by kuhnroyal** [comment]
Maybe, I am not sure.

**Comment by mattiLeBlanc** [comment]
okay. well I will test the code a bit further, by building my app in the foundation and see if it happens again, kay?

Thanks
